openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: TODO
  title: Default
  description: |-
  
    A default is a special variable that has a context associated with
    it. This allows one to define values that can be easily retrieved
    based on the associated context. For example, a default could be
    the image name for a cloud where the context is defined by the
    cloud name. In addition to the context, the service name is also specified
    since a service could have multiple contexts. To be able to
    define the kind of service there is also a kind attribute.
    
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /default:
    get:
      tags:
        - Default
      summary: Returns all defaults
      description: Returns all defaults
      operationId: cloudmesh.default.get
      responses:
        "200":
          description: default info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Default"
    put:
      tags:
        - Default
      summary: Create a new default
      description: Create a new default
      operationId: cloudmesh.default.add
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Default"
        description: The new default to create
        required: true
      responses:
        "201":
          description: Created
  "/default/{name}":
    get:
      tags:
        - Default
      summary: Returns a default
      description: Returns a default
      operationId: cloudmesh.default.get_by_name
      parameters:
        - name: name
          in: path
          required: true
          description: The name of the default
          schema:
            type: string
      responses:
        "200":
          description: default info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
components:
  schemas:
    Default:
      type: object
      description: the defaults
      properties:
        name:
          type: string
          description: The name of the default
        value:
          type: string
          description: The type of the default
        kind:
          type: string
          description: The value of the default
        service:
          type: string
          description: The name of the service
        context:
          type: string
          description: The context of the service