openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: TODO
  title: Reservation
  description: |-
  
    Some services may consume a considerable amount of resources,
    necessitating the reservation of resources.
    
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /reservations:
    get:
      tags:
      - Reservation
      summary: Returns all reservations
      description: Returns all reservations
      operationId: cloudmesh.reservation.get
      responses:
        200:
          description: reservation info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Reservation"
    put:
      tags:
      - Reservation
      summary: Create a new reservation
      description: Create a new reservation
      operationId: cloudmesh.reservation.add
      parameters:
        - in: path
          name: reservation
          description: The new reservation to create
          schema:
            $ref: "#/components/schemas/Reservation"
      responses:
        "201":
          description: Created
  "/reservation/{name}":
    get:
      tags:
      - Reservation
      summary: Returns a reservation
      description: Returns a reservation
      operationId: cloudmesh.reservation.get_by_name
      parameters:
        - name: name
          description: Get reservation info by name
          in: path
          required: true
          type: string
      responses:
        200:
          description: reservation info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reservation"
    put:
      tags:
        - Reservation
      summary: Uploads a reservation by name
      description: Uploads a reservation by name
      operationId: cloudmesh.reservation.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the reservation
      responses:
        200:
          description: reservation info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reservation"
    delete:
      tags:
        - Reservation
      summary: Deletes a reservation by name
      description: Deletes a reservation by name
      operationId: cloudmesh.reservation.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the reservation
      responses:
        200:
          description: reservation info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reservation"
components:
  schemas:
    Reservation:
      type: object
      description: the reservation
      properties:
        name:
          type: string
          description: name of the reservation
        service:
          type: string
          description: the name of the service on which we reserve
        description:
          type: string
          description: the description of the reservation
        start:
          type: string
          format: date
          description: the start time and date
        end:
          type: string
          format: date
          description: the end time and date
        timestamp:
          description: timestamps associated with the resource
          $ref: "timestamp.yaml#/components/schemas/Timestamp"
