openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: TODO
  title: Scheduler
  description: |-
  
    The scheduler is a service to store scheduler, value, and type information, all of which
    are stored as strings.
    
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /scheduler:
    get:
      tags:
      - Scheduler
      summary: Returns all schedulers
      description: Returns all schedulers
      operationId: cloudmesh.scheduler.get
      responses:
        '200':
          description: scheduler info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Scheduler"
    put:
      tags:
      - Scheduler
      summary: Create a new scheduler
      description: Create a new scheduler
      operationId: cloudmesh.scheduler.add
      parameters:
        - in: path
          name: scheduler
          description: The new scheduler to create
          schema:
            $ref: "#/components/schemas/Scheduler"
      responses:
        "201":
          description: Created
  "/scheduler/{name}":
    get:
      tags:
      - Scheduler
      summary: Returns a scheduler
      description: Returns a scheduler
      operationId: cloudmesh.scheduler.get_by_name
      parameters:
        - name: name
          description: name of the scheduler
          in: path
          required: true
          type: string
      responses:
        '200':
          description: scheduler info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Scheduler"
    put:
      tags:
        - Scheduler
      summary: Uploads a scheduler by name
      description: Uploads a scheduler by name
      operationId: cloudmesh.scheduler.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the scheduler
      responses:
        '200':
          description: scheduler info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Scheduler"
    delete:
      tags:
        - Scheduler
      summary: Deletes a scheduler by name
      description: Deletes a scheduler by name
      operationId: cloudmesh.scheduler.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the scheduler
      responses:
        '200':
          description: scheduler info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Scheduler"
components:
  schemas:
    Scheduler:
      type: object
      description: the scheduler
      properties:
        name:
          type: string
          description: name of the scheduler
        value:
          type: string
          description: information of the scheduler
        kind:
          type: string
          description: the scheduler kind or type
        timestamp:
          description: timestamps associated with the resource
          $ref: "timestamp.yaml#/components/schemas/Timestamp"
