openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: TODO
  title: Variables
  description: |-
  
    Variables are used to store simple values. Each variable can have
    a type, which is also provided as demonstrated in the object
    below. The variable value format is defined as string to allow
    maximal probability.
    
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /variables:
    get:
      tags:
        - Variables
      summary: Returns all variabless
      description: Returns all variabless
      operationId: cloudmesh.variables.get
      responses:
        200:
          description: variables info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Variables"
    put:
      tags:
        - Variables
      summary: Create a new variables
      description: Create a new variables
      operationId: cloudmesh.variables.add
      parameters:
        - in: path
          name: variables
          description: The new variables to create
          schema:
            $ref: "#/components/schemas/Variables"
      responses:
        201:
          description: Created
  "/variables/{name}":
    get:
      tags:
        - Variables
      summary: Returns a variables
      description: Returns a variables
      operationId: cloudmesh.variables.get_by_name
      parameters:
        - name: name
          description: Name of the variable
          in: path
          required: true
          type: string
      responses:
        200:
          description: variables info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Variables"
components:
  schemas:
    Variables:
      type: object
      description: the variables
      properties:
        name:
          type: string
          description: name of the variable
        value:
          type: string
          description: type of the variable
        kind:
          type: string
          description: value of the variable
        timestamp:
          description: timestamps associated with the resource
          $ref: "timestamp.yaml#/components/schemas/Timestamp"
