
openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: TODO
  title: Virtual Directory
  description: |-
  
    A virtual directory is a collection of files or replicas of the
    files.  A virtual directory can contain a number of entities
    including files, streams, and other virtual directories as part of
    a collection.  The element in the collection can either be defined
    by uuid or by name.

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup Service
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /virtualdirectory:
    get:
      tags:
        - Virtualdirectory
      summary: Returns all virtualdirectorys
      description: Returns all virtualdirectorys
      operationId: cloudmesh.virtualdirectory.get
      responses:
        '200':
          description: virtualdirectory info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Virtualdirectory"
        "401":
          description: unauthorized error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
    put:
      tags:
        - Virtualdirectory
      summary: Create a new virtualdirectory
      description: Create a new virtualdirectory
      operationId: cloudmesh.virtualdirectory.add
      parameters:
        - in: path
          name: virtualdirectory
          required: true
          description: The new virtualdirectory to create
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Virtualdirectory"
      responses:
        "201":
          description: Created
  "/virtualdirectory/{name}":
    get:
      tags:
        - Virtualdirectory
      summary: Returns a virtualdirectory by name
      description: Returns a virtualdirectory by name
      operationId: cloudmesh.virtualdirectory.get_by_name
      parameters:
        - name: name
          description: name of the virtual directory
          in: path
          required: true
          type: string
      responses:
        '200':
          description: virtualdirectory info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Virtualdirectory"
components:
  schemas:
    UnauthorizedError:
      type: object
      description: unauthorized error
      properties:
        code:
          type: string
          description: Code form of the error
        message:
          type: string
          description: Human readable form of the error
    Virtualdirectory:
      type: object
      description: the virtualdirectory
      properties:
        name:
          description: The name of the virtual directory
          type: string
        description:
          description: description of the virtual directory
          type: string
        host:
          description: remote host of the virtual directory
          type: string
        location:
          description: remote location, e.g., a directory with full path on a host
          type: string
        protocol:
          description: access protocol, e.g., HTTP, FTP, SSH, etc.
          type: string
        credential:
          description: credential to access, e.g., username, password
          type: object
        timestamp:
          description: timestamps associated with the resource
          $ref: "timestamp.yaml#/components/schemas/Timestamp"

