openapi: "3.0.2"
info:
  version: "3.1.1"
  x-status: defined
  x-date: 02-15-2019
  title: Cloudmesh NIST BDRA Specification API
  description:
  termsOfService: "https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
  license:
    name: Apache
host: localhost:8080
externalDocs:
  description: more infortion abut the NIST BDRA
  url: https://github.com/cloudmesh-community/nist/blob/master/docs/nistvol8-2.epub?raw=true
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  httpbasic:
    type: basic
  apikey:
    type: apiKey
    in: query
    name: api_key
  apisecret:
    type: apiKey
    in: query
    name: api_secret