openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: defined
  title: Cloudmesh NIST BDRA Specification API Example
  description: |-

    Each user should be part of at least one account with a specific charge and quota 
    that determines how much more resources the users of that account are allowed to use. 
    It is of course possible for a user to be part of several accounts. 

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
  license:
    name: Apache
host: localhost:8080
externalDocs:
  description: more infortion abut the NIST BDRA
  url: https://github.com/cloudmesh-community/nist/blob/master/docs/nistvol8-2.epub?raw=true
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
basePath: "/cloudmesh/v3"
paths:
  /accounting/key:
    get:
      tags:
        - Accounting
      summary: Returns all keys with their values and types included
      description: Returns all keys with their values and types included
      operationId: cloudmesh.accounting.get
      produces:
        - application/json
      responses:
        200:
          description: key info
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Account"
    put:
      tags:
        - Accounting
      summary: Create a new key
      description: Create a new key
      operationId: cloudmesh.accounting.put
      parameters:
        - in: body
          name: key
          description: The new key to create
          required: true
          schema:
            $ref: "#/components/schemas/Account"
      responses:
        "201":
          description: Created
  /accounting/key/{name}:
    get:
      tags:
        - Accounting
      summary: Returns the key with its detailed information by name of the key
      description: Returns the key with its detailed information by name of the key
      operationId: cloudmesh.accounting.get_by_name
      parameters:
        - name: name
          description: name of the key
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: key info
          schema:
            $ref: "#/components/schemas/Account"
components:
  schemas:
    Account:
      type: object
      description: account information including finances and summary.
      properties:
        name:
          type: string
          description: name of account
        users:
          type: array
          description: The username the charge is made for
          items:
            $ref: "user.yaml#/components/schemas/User"
        organization:
           description: the organization this chargi is made for
           $ref: "organization.yaml#/components/schemas/Organization"
        group:
          type: string
          description: a name of a group this acount belongs to
        purpose:
          type: string
          description: the purpose of the account
        charge:
          type: integer
          minimum: 0
          description: The current chare of the account
        unit:
           type: string
           description: the unit in which the account is charged and the charge value is stored
