openapi: '3.0.2'
info:
  version: 3.2.0
  x-date: 008-06-2019
  x-status: defined
  title: Alias
  description: |-

    Often a user has the desire to create a custom name for an object. An
    alias allows to do that while while assosication auser defined name or
    *alias* to a previouly used name. The aliases could be shared with other
    users. A name could have one or more aliases.

  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /alias:
    get:
      tags:
        - Alias
      summary: Returns a list of aliases
      description: Returns a list of all aliases
      operationId: cloudmesh.alias.list
      responses:
        '200':
          description: The list of aliasses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alias'
        '400':
           description: No Alias found.
        '401':
          description: Not authorized.
    put:
      tags:
        - Alias
      summary: Set an alias
      description: Sets the named alias
      operationId: cloudmesh.alias.add
      requestBody:
        description: The new alias to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alias'
      responses:
        '200':
          description: Alias updated.
        '400':
          description: Error updateing alias.
        '401':
          description: Not authorized.
  /alias/{name}:
    get:
      tags:
        - Alias
      summary: Returns the named alias
      description: Returns an alias by name
      operationId: cloudmesh.alias.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the alias
      responses:
        '200':
          description: Returning the information of the alias
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alias'
        '400':
           description: No Alias found.
        '401':
          description: Not authorized.
        '404':
           description: The named alias could not be found.
    delete:
      tags:
        - Alias
      summary: Deletes the named alias
      description: Deletes an alias by name
      operationId: cloudmesh.alias.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the alias
      responses:
        '200':
          description: Deletion successful.
        '400':
           description: No Alias found.
        '401':
          description: Not authorized.
        '404':
           description: The named alias could not be found.
components:
  schemas:
    Alias:
      type: object
      description: the alias
      properties:
        name:
          type: string
          description: The name of the alias
        source:
          type: string
          description: The original object name

