openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: defined
  title: Alias
  description: |-

    A user may desire to create an alias for a resource. An alias helps users to
    distinguish a resource more easily. A User can deploy a service in which such
    aliases are stored. The aliases could naturally be shared with other users. 
    A resource could have one or more aliases. The reason for using an alias is 
    that a resource may have a complex name but a user may want to refer to the 
    resource using a name that is suitable for the users" application.

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
basePath: "/cloudmesh/v3"
paths:
  /alias:
    get:
      tags:
        - Alias
      summary: Returns a list of aliases
      description: Returns a list of aliases
      operationId: cloudmesh.alias.get
      produces:
        - application/json
      responses:
        200:
          description: alias information
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Alias"
    put:
      tags:
        - Alias
      summary: Create a new alias
      description: Create a new alias
      operationId: cloudmesh.alias.put
      parameters:
        - in: body
          name: alias
          required: true
          description: The new alias to create
          schema:
            $ref: "#/components/schemas/Alias"
      responses:
        "201":
          description: Created
  "/alias/{name}":
    get:
      tags:
        - Alias
      summary: Returns an alias by name
      description: Returns an alias by name
      operationId: cloudmesh.alias.get_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the alias
      produces:
        - application/json
      responses:
        200:
          description: alias info
          schema:
            $ref: "#/components/schemas/Alias"
components:
  schemas:
    Alias:
      type: object
      description: the alias
      properties:
        name:
          type: string
          description: The name of the alias
        origin:
          type: string
          description: The original object name
        timestamp:
          description: timestamps associated with the resource
          $ref: "timestamp.yaml#/components/schemas/Timestamp"
