openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: defined
  title: Alias
  description: |-

    Often a user has the desire to create a custom name for an object. An
    alias allows to do that while while assosication auser defined name or
    *alias* to a previouly used name. The aliases could be shared with other
    users. A name could have one or more aliases.

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt

servers:
  - url: /cloudmesh/v3
paths:
  /alias:
    get:
      tags:
        - Alias
      summary: Returns a list of aliases
      description: Returns a list of all aliases
      operationId: cloudmesh.alias.get
      responses:
        "200":
          description: The list of Aliasses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Alias"
        "400":
          description: No Alias found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Alias
      summary: Create a new alias
      description: Create a new alias
      operationId: cloudmesh.alias.put
      parameters:
        - in: query
          name: alias
          required: true
          description: The new alias to create
          schema:
            $ref: "#/components/schemas/Alias"
      responses:
        "200":
          description: Created
  "/alias/{name}":
    get:
      tags:
        - Alias
      summary: Returns an alias by name
      description: Returns an alias by name
      operationId: cloudmesh.alias.get_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the alias
      responses:
        200:
          description: Retruning the information of the alias
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Alias"
components:
  schemas:
    Alias:
      type: object
      description: the alias
      properties:
        name:
          type: string
          description: The name of the alias
        source:
          type: string
          description: The original object name
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
