openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 17-06-2019
  x-status: defined
  title: Containers
  description: |-

    Numerous different containers are likely to be created and handling them 
    becomes more and more time consuming as their number increases. This service 
    helps to solve that issue by storing containers and their corresponding 
    information. 

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /container:
    get:
      tags:
        - Container
      summary: Returns a list of containers
      description: Returns a list of all containers
      operationId: cloudmesh.container.list
      responses:
        '200':
          description: The list of containerses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Container'
        '401':
          description: Not authorized
  /container/{name}:
    get:
      tags:
        - Container
      summary: Returns the named container
      description: Returns an container by name
      operationId: cloudmesh.container.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the container
      responses:
        '200':
          description: Returning the information of the container
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Container'
        '400':
           description: No Container found
        '401':
          description: Not authorized
        '404':
           description: The named container could not be found
    put:
      tags:
        - Container
      summary: Set an container
      description: Sets the named container
      operationId: cloudmesh.container.add
      requestBody:
        description: The new container to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Container'
      responses:
        '200':
          description: Container updated
        '401':
          description: Not authorized
        '400':
          description: Error updating container
    delete:
      tags:
        - Container
      summary: Deletes the named container
      description: Deletes an container by name
      operationId: cloudmesh.container.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the container
      responses:
        '200':
          description: Deletion successful
        '401':
          description: Not authorized
        '404':
           description: The named container could not be found
components:
  schemas:
    Container:
      type: object
      description: A record representing a container
      properties:
        name:
          type: string
          description: Name of the container
        version:
          type: string
          description: Version of the container
        label:
          type: string
          description: Label of the container
        type:
          type: string
          description: Type of the container
        definition:
          type: string
          description: Definition or manifest of the container
        imgURI:
          type: string
          description: URI of the container
        tags:
          type: array
          description: Tags of the container
          items:
            type: string
