swagger: "2.0"
info:
  version: 3.1.1
  x-status: defined
  x-date: 02-15-2019
  title: Database
  description: |-
  
    There are several types of databases used in the wild and this service helps 
    to keep track of them. A database record could have a name, an endpoint 
    (e.g., host, port), and a protocol used (e.g., SQL, MongoDB).

  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/database:
    get:
      tags:
        - Database
      summary: Returns all databases
      description: Returns all databases
      operationId: cloudmesh.database.get
      produces:
        - application/json
      responses:
        200:
          description: database info
          schema:
            type: array
            items:
              $ref: '#/definitions/Database'
    put:
      tags:
        - Database
      summary: Create a new database
      description: Create a new database      
      operationId: cloudmesh.database.put
      parameters:
        - in: body
          name: database
          required: true
          description: The new database record to create
          schema:
            $ref: '#/definitions/Database'
      responses:
        201:
          description: Created
  '/cloudmesh/database/{name}':
    get:
      tags:
        - Database
      summary: Returns a database by name
      description: Returns a database by name
      operationId: cloudmesh.database.get_by_name
      parameters:
        - name: name
          description: name of the database
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: database info
          schema:
            $ref: '#/definitions/Database'
definitions:
  Database:
    type: object
    description: defines a database object as an entry
    properties:
      name:
        type: string
        description: name of the database
      description:
        type: string
        description: description of the database
      endpoint:
        type: string
        description: endpoint of the database
      kind:
        type: string
        description: the kind of the database
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'
