openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 008-06-2019
  x-status: TODO
  title: Database
  description: |-

    The database specification allows to register a database and perform
    elementary operations to use this database. We distinguish actions
    related to the registration, the adding of a schema, the insertion of
    data and the query of data. The data base is defined by a name an endpoint
    (e.g., host, port), and a protocol used (e.g., SQL, MongoDB, graphgl, and
     others).

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /database:
    get:
      tags:
        - "Database Registry"
      summary: Returns all databases
      description: Returns all databases
      operationId: cloudmesh.database.get
      responses:
        '200':
          description: database info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Database"
        '400':
          description: No database found
        '401':
          description: Not authorized.
        '404':
          description: Named database not found
    delete:
      tags:
        - "Database Registry"
      summary: Deletes a database from the list of databases
      description: Deletes a database from the list of databases
      operationId: cloudmesh.database.delete
      parameters:
        - name: name
          description: name of the database
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: database info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Database"
        '400':
          description: No database found
        '401':
          description: Not authorized.
        '404':
          description: Named database not found
  /database/{name}:
    get:
      tags:
      - "Database Definition"
      summary: "Get the list of tables or collections for the database"
      description: ""
      operationId: "cloudmesh.database.get.collections_or_tables"
      parameters:
        - name: name
          description: name of the collections or tables
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "successfully returned the list"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Definition"
        '400':
          description: No database found
        '401':
          description: Not authorized.
        '404':
          description: Named database not found
    put:
      tags:
      - "Database Definition"
      summary: "Upload  a news table or collection"
      description: ""
      operationId: "cloudmesh.database.put.collections_or_tables"
      parameters:
        - name: name
          description: name of the collections or tables
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "successfully returned the list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Definition"
        '400':
          description: No database found
        '401':
          description: Not authorized.
        '404':
          description: Named database not found
  /database/{name}/{table_or_collection}:
    get:
      tags:
      - "Database Data Interaction"
      summary: "Query the table or collection"
      description: ""
      operationId: "cloudmesh.database.data.get"
      parameters:
      - name: name
        description: name of the database
        in: path
        required: true
        schema:
          type: string
      - name: table_or_collection
        description: name of the table or collection
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Database Query
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '200':
          description: successfull query
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Record"
        '400':
          description: No database found
        '401':
          description: Not authorized.
        '404':
          description: Named database not found
    put:
      tags:
      - "Database Data Interaction"
      summary: "add data to the table or collection"
      description: ""
      operationId: "cloudmesh.database.data.put"
      parameters:
      - name: name
        description: name of the database
        in: path
        required: true
        schema:
          type: string
      - name: table_or_collection
        description: name of the table or collection
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Record to be uploaded
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Record"
      responses:
        '200':
          description: "successfully uploaded"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Record"
        '400':
          description: No database found
        '401':
          description: Not authorized.
        '404':
          description: Named database not found
components:
  schemas:
    Database:
      type: object
      description: defines a database object as an entry
      properties:
        name:
          type: string
          description: name of the database
        description:
          type: string
          description: description of the database
        endpoint:
          type: string
          description: endpoint of the database
        kind:
          type: string
          description: the kind of the database
        timestamp:
          description: timestamps associated with the resource
          $ref: "timestamp.yaml#/components/schemas/Timestamp"
    Definition:
      type: object
      description: defines a database collection or Table
      properties:
        name:
          type: string
          description: name of the database
        description:
          type: string
          description: description of the database
        kind:
          type: string
          description: the kind of the definition
        schema:
           type: string
           description: the schema associated with the table or collection
        timestamp:
          description: timestamps associated with the resource
          $ref: "timestamp.yaml#/components/schemas/Timestamp"
    Record:
      type: object
      description: The result of a query
      properties:
        status:
          type: string
          description: The status of the reurn
        result:
          type: string
          description: The result of the quesry in json string format
    Query:
      type: object
      description: The  query
      properties:
        status:
          type: string
          description: The query string

