swagger: "2.0"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: defined
  title: Database
  description: |-
  
    The database specification allows to register a database and perform
    elementary operations to use this database. We distinguish actions
    related to the registration, the adding of a schema, the insertion of
    data and the query of data. The data base is defined by a name an endpoint
    (e.g., host, port), and a protocol used (e.g., SQL, MongoDB, graphgl, and
     others).

  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
basePath: "/cloudmesh/v3"
paths:
  /database:
    get:
      tags:
        - database
      summary: Returns all databases
      description: Returns all databases
      operationId: cloudmesh.database.get
      produces:
        - application/json
      responses:
        200:
          description: database info
          schema:
            type: array
            items:
              $ref: '#/definitions/Database'
        400:
          description: "Invalid name supplied"
        401:
          description: "Invalid credentials"
        404:
          description: "Database not found"
    put:
      tags:
        - database
      summary: Create a new database
      description: Create a new database
      operationId: cloudmesh.database.put
      parameters:
        - in: body
          name: database
          descriptiion: The new database specification
          required: true
          schema:
            $ref: '#/definitions/Database'
      responses:
        201:
          description: Created
  '/database/{name}':
    get:
      tags:
        - database
      summary: Returns a database by name
      description: Returns a database by name
      operationId: cloudmesh.database.get_by_name
      parameters:
        - name: name
          description: name of the database
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: database info
          schema:
            $ref: '#/definitions/Database'
  "database/{name}/delete":
     tags:
       - database
     summary: Deletes a database from the list of databases
     description: Deletes a database from the list of databases
     operationId: cloudmesh.database.delete
     parameters:
       - name: name
         description: name of the database
         in: path
         required: true
         type: string
     produces:
       - application/json
     responses:
       200:
         description: database info
         schema:
           $ref: '#/definitions/Database'
       400:
         description: "Invalid name supplied"
       404:
         description: "Database Information not found"
   /database/{name}/query:
      patch:
        tags:
        - "database"
        summary: "Query a database"
        description: ""
        operationId: "cloudmesh.database.query"
        produces:
        - "application/json"
        parameters:
         - name: name
           description: name of the database
           in: path
           required: true
           type: string
        - name: "query"
          in: "query"
          description: "Database Query"
          required: true
          type: "string"
          format: base64
        responses:
          200:
            description: "successfully ran the Query"
            schema:
              $ref: "#/definitions/database"
          400:
            description: "Invalid name supplied"
          401:
            description: "Invalid credentials"
          405:
            description: "Invalid input"
   /database/{name}/import:
      patch:
        tags:
        - "database"
        summary: "Bulk add information in the database"
        description: ""
        operationId: "cloudmesh.database.add"
        produces:
        - "application/json"
        parameters:
         - name: name
           description: name of the database
           in: path
           required: true
           type: string
        - name: "add"
          in: "query"
          description: "Database Add"
          required: true
          type: "string"
          format: base64
        responses:
          200:
            description: "successfully ran the Import"
            schema:
              $ref: "#/definitions/database"
          400:
            description: "Invalid name supplied"
          401:
            description: "Invalid credentials"
          405:
            description: "Invalid input"
   /database/{name}/add:
      patch:
        tags:
        - "database"
        summary: "Add information in the database"
        description: ""
        operationId: "cloudmesh.database.add"
        produces:
        - "application/json"
        parameters:
         - name: name
           description: name of the database
           in: path
           required: true
           type: string
        - name: "add"
          in: "query"
          description: "Database Add"
          required: true
          type: "string"
          format: base64
        responses:
          200:
            description: "successfully added information to database"
            schema:
              $ref: "#/definitions/database"
          400:
            description: "Invalid name supplied"
          401:
            description: "Invalid credentials"
          405:
            description: "Invalid input"

   /database/{name}/modify:
      patch:
        tags:
        - "database"
        summary: "Modify information in the database (DDL/DML/change/modify operations)"
        description: ""
        operationId: "cloudmesh.database.modify"
        produces:
        - "application/json"
        parameters:
         - name: name
           description: name of the database
           in: path
           required: true
           type: string
        - name: "modify"
          in: "query"
          description: "Database Modififation"
          required: true
          type: "string"
          format: base64
        responses:
          200:
            description: "successfully ran the modifications"
            schema:
              $ref: "#/definitions/database"
          400:
            description: "Invalid name supplied"
          401:
            description: "Invalid credentials"
          405:
            description: "Invalid input"
definitions:
  Database:
    type: object
    description: defines a database object as an entry
    properties:
      name:
        type: string
        description: name of the database
      description:
        type: string
        description: description of the database
      endpoint:
        type: string
        description: endpoint of the database
      kind:
        type: string
        description: the kind of the database
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'
