openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: defined
  title: Default
  description: |-
  
    A default is a special variable that has a context associated with
    it. This allows one to define values that can be easily retrieved
    based on the associated context. For example, a default could be
    the image name for a cloud where the context is defined by the
    cloud name. In addition to the context, the service name is also specified
    since a service could have multiple contexts. To be able to
    define the kind of service there is also a kind attribute.
    
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /default:
    get:
      tags:
        - Default
      summary: Returns a list of defaults
      description: Returns a list of all defaults
      operationId: cloudmesh.default.list
      responses:
        '200':
          description: The list of defaults
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Default'
        '400':
           description: No Default found.
    put:
      tags:
        - Default
      summary: Set a default
      description: Sets the named default
      operationId: cloudmesh.default.add
      requestBody:
        description: The new default to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Default'
      responses:
        '200':
          description: Default updated.
        '400':
          description: Error updateing default.
  /default/{name}:
    get:
      tags:
        - Default
      summary: Returns the named default
      description: Returns a default by name
      operationId: cloudmesh.default.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the default
      responses:
        '200':
          description: Retruning the information of the default
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Default'
        '400':
           description: No Default found.
        '404':
           description: The named default could not be found.
    delete:
      tags:
        - Default
      summary: Deletes the named default
      description: Deletes a default by name
      operationId: cloudmesh.default.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the default
      responses:
        '200':
          description: Deletion successful.
        '400':
           description: No Default found.
        '404':
           description: The named default could not be found.
components:
  schemas:
    Default:
      type: object
      description: the defaults
      properties:
        name:
          type: string
          description: The name of the default
          example: "image"
        value:
          type: string
          description: The value of the default
          example: "m1.medium"
        context:
          type: string
          description: The context of the default
          example: "cloud.vm.flavor"