swagger: "2.0"
info:
  version: 3.1.1
  x-status: defined
  x-date: 02-15-2019
  title: Default
  description: |-
  
    A default is a special variable that has a context associated with
    it. This allows one to define values that can be easily retrieved
    based on the associated context. For example, a default could be
    the image name for a cloud where the context is defined by the
    cloud name. In addition to the context, the service name is also specified
    since a service could have multiple contexts. To be able to
    define the kind of service there is also a kind attribute.
    
  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/default:
    get:
      tags:
        - Default
      summary: Returns all defaults
      description: Returns all defaults
      operationId: cloudmesh.default.get
      produces:
        - application/json
      responses:
        '200':
          description: default info
          schema:
            type: array
            items:
              $ref: '#/definitions/Default'
    put:
      tags:
        - Default
      summary: Create a new default
      description: Create a new default
      operationId: cloudmesh.default.add
      parameters:
        - in: body
          name: default
          required: true
          description: The new default to create
          schema:
            $ref: '#/definitions/Default'
      responses:
        '201':
          description: Created
  '/cloudmesh/default/{name}':
    get:
      tags:
        - Default
      summary: Returns a default
      description: Returns a default
      operationId: cloudmesh.default.get_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the default
      produces:
        - application/json
      responses:
        '200':
          description: default info
          schema:
            $ref: '#/definitions/Default'
definitions:
  Default:
    type: object
    description: the defaults
    properties:
      name:
        type: string
        description: The name of the default
      value:
        type: string
        description: The type of the default
      kind:
        type: string
        description: The value of the default
      service:
        type: string
        description: The name of the service
      context:
        type: string
        description: The context of the service
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'
