openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 17-06-2019
  x-status: defined
  title: Deployment
  description: |-
  
    A resource to store software deployments. The deployment is formulated in
    aspecification file. To distinguish the format of the specification file
    a string is used that defines the kind of the deployment. In case the
    specification uses an  external service an endpoint to the service can
    be used and the name of the specification is used to identify the
    deployment.
    
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /deployment:
    get:
      tags:
        - Deployment
      summary: Returns a list of deploymentes
      description: Returns a list of all deploymentes
      operationId: cloudmesh.deployment.list
      responses:
        '200':
          description: The list of deploymentses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Deployment'
        '401':
          description: Not authorized
  /deployment/{name}:
    get:
      tags:
        - Deployment
      summary: Returns the named deployment
      description: Returns an deployment by name
      operationId: cloudmesh.deployment.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the deployment
      responses:
        '200':
          description: Returning the information of the deployment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
        '401':
          description: Not authorized
        '404':
           description: The named deployment could not be found
    put:
      tags:
        - Deployment
      summary: Set an deployment
      description: Sets the named deployment
      operationId: cloudmesh.deployment.add
      requestBody:
        description: The new deployment to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Deployment'
      responses:
        '200':
          description: Deployment updated
        '401':
          description: Not authorized
    delete:
      tags:
        - Deployment
      summary: Deletes the named deployment
      description: Deletes an deployment by name
      operationId: cloudmesh.deployment.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the deployment
      responses:
        '200':
          description: Deletion successful
        '401':
          description: Not authorized
        '404':
           description: The named deployment could not be found
components:
  schemas:
    Deployment:
      type: object
      description: the deployment
      properties:
        name:
          type: string
          description: The name of the deployment
        kind:
          type: string
          description: The kind of the deployment
        specification:
          type: string
          description: The specification of the deployment
        endpoint:
          type: string
          description: The location of the deployment service
        endpointname:
          type: string
          description: in case an endpoint is used, the endpointname is used
                       to uniquly identify the deployment within the
                       endpoint defined service