openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 17-06-2019
  x-status: defined
  title: File
  description: |-
  
    A file store is a resource allowing storage of data as a traditional file.
    A file store can contanin any number of files with additional attributes
    describing the file. A file store is located on the physical  server. It
    contains access to the content of the file. This contrasts virtual
    directories that are just pointers to files, which could include files
    located in different file stores. A  virtual directory also doe snot
    contain the content of the file, but just a pointer where to find the file.

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /file:
    get:
      tags:
        - File
      summary: Returns a list of files in the file store
      description: Returns a list of all files
      operationId: cloudmesh.file.list
      responses:
        '200':
          description: The list of files
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/File'
        '401':
          description: Not authorized
  /file/{name}:
    get:
      tags:
        - File
      summary: Returns the named file in the file store
      description: Returns an file by name in the file store
      operationId: cloudmesh.file.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the file
      responses:
        '200':
          description: Returning the information of the file store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        '401':
          description: Not authorized
        '404':
          description: The named file could not be found
    put:
      tags:
        - File
      summary: Uploads a file to the list of files in the file store
      description: Uploads a file to the list of files in the file store
      operationId: cloudmesh.file.add
      requestBody:
        description: The file to be uploaded
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/File'
      responses:
        '200':
          description: File updated or created
        '401':
          description: Not authorized
    delete:
      tags:
        - File
      summary: Deletes the named file in the file store
      description: Deletes an file by name
      operationId: cloudmesh.file.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the file
      responses:
        '200':
          description: Deletion successful
        '401':
          description: Not authorized
        '404':
          description: The named file could not be found
components:
  schemas:
    File:
      type: object
      description: an object representing a file
      properties:
        name:
          type: string
          description: The name of the file
        endpoint:
          type: string
          description: The location of the file
        checksum:
          type: string
          description: The checksum of the file
        size:
          type: integer
          description: The size of the file in byte
        content:
          type: string
          format: binary
          description: the content of the file



