openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: defined
  title: File
  description: |-
  
    A file is a resource allowing storage of data as a traditional file
    being processed. The interface to a file provides the mechanism to
    appropriately locate a file in a distributed system. File
    identification includes the name, endpoint, checksum, and
    size. Additional parameters, such as a timestamp can
    also be stored. The interface only describes the location of the
    file.  The file object has name, endpoint (location), size (in gigabytes [GB],
    megabytes [MB], and Bytes), and checksum for integrity check.
    
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /file:
    get:
      tags:
      - File
      summary: Returns all files
      description: Returns all files
      operationId: cloudmesh.file.get
      responses:
        200:
          description: file info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/File"
    put:
      tags:
      - File
      summary: Create a new file
      description: Create a new file      
      operationId: cloudmesh.file.put
      parameters:
        - in: body
          name: file
          required: true
          description: The new file record to create
          schema:
            $ref: "#/components/schemas/File"
      responses:
        "201":
          description: Created
  "/file/{name}":
    get:
      tags:
      - File
      summary: Returns a file by name
      description: Returns a file by name
      operationId: cloudmesh.file.get_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the file
      responses:
        200:
          description: file info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
    put:
      tags:
        - File
      summary: Uploads a file by name
      description: Uploads a file by name
      operationId: cloudmesh.file.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the file
      responses:
        200:
          description: file info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
    delete:
      tags:
        - File
      summary: Deletes a file by name
      description: Deletes a file by name
      operationId: cloudmesh.file.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the file
      responses:
        200:
          description: file info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
components:
  schemas:
    File:
      type: object
      description: an object representing a file
      properties:
        name:
          type: string
          description: The name of the file
        endpoint:
          type: string
          description: The location of the file
        checksum:
          type: string
          description: The checksum of the file
        size:
          type: integer
          description: The size of the file in byte
        timestamp:
          description: timestamps associated with the file
          $ref: "timestamp.yaml#/components/schemas/Timestamp"


