openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: defined
  title: Image
  description: |-
  
    Image defines an object representing a system image
    in a cloud that can be used to start virtual machines.
    
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /image:
    get:
      tags:
      - Image
      summary: Returns all general description images
      description: Returns all general description images
      operationId: cloudmesh.image.get
      responses:
        200:
          description: default image info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Image"
    put:
      tags:
      - Image
      summary: Create a new image
      description: Create a new image
      operationId: cloudmesh.image.put
      parameters:
        - in: body
          name: image
          required: true
          description: The new image record to create
          schema:
            $ref: "#/components/schemas/Image"
      responses:
        "201":
          description: Created
  "/image/{name}":
    get:
      tags:
      - Image
      summary: Returns general description of an image
      description: Returns general description of an image
      operationId: cloudmesh.image.get_by_name
      parameters:
        - name: name
          description: name of the image
          in: path
          required: true
          type: string
      responses:
        200:
          description: image info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
    put:
      tags:
        - Image
      summary: Uploads a image by name
      description: Uploads a image by name
      operationId: cloudmesh.image.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the image
      responses:
        200:
          description: image info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
    delete:
      tags:
        - Image
      summary: Deletes a image by name
      description: Deletes a image by name
      operationId: cloudmesh.image.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the image
      responses:
        200:
          description: image info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
components:
  schemas:
    Image:
      type: object
      properties:
        id:
          type: string
          description: A unique id for the image
        name:
          type: string
          description: Name of the image
        label:
          type: string
          description: A label that can be defined by the user for the image
        description:
          type: string
          description: A description for the image
        collection:
          type: string
          description: The collection in which the image fits
        cloud:
          type: string
          description: A cloud provider for which the image is designed. If multiple are using the image, they are passed along as space separated strings
        os_type:
          type: string
          description: The OS of the image
        osVersion:
          type: string
          description: The OS version of the image
        min_requirement:
          $ref: "#/components/schemas/Minimum_Requirements"
          description: minimum requirement to run the image
        status:
          type: string
          description: The status of the image
        progress:
          type: integer
          description: The loading progress percentage of the image
        visibility:
          description: The visibility of the image
          type: string
        timestamp:
          description: timestamps associated with the image
          $ref: "timestamp.yaml#/components/schemas/Timestamp"
    Minimum_Requirements:
      type: object
      properties:
        disk_space:
          type: integer
          description: Minimum disk space in bytes required for the image
        ram:
          type: integer
          description: Minimum ram size in bytes to run the image
        cpu:
          type: string
          description: Minimum CPU required to run the image including number of cores and clock speed
