openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: TODO
  title: MapReduce
  description: |-
  
    A service to store the information of a mapreduce deployment definition.
    All of the attributes are stored as Strings.
    
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /mapreduce:
    get:
      tags:
      - mapreduce
      summary: Returns all mapreduces
      description: Returns all mapreduces
      operationId: cloudmesh.mapreduce.get
      responses:
        200:
          description: mapreduce info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/mapreduce"
    put:
      tags:
      - mapreduce
      summary: Create a new mapreduce
      description: Create a new mapreduce
      operationId: cloudmesh.mapreduce.put
      parameters:
        - in: body
          name: mapreduce
          description: The new mapreduce to create
          schema:
            $ref: "#/components/schemas/mapreduce"
      responses:
        "201":
          description: Created
  "/mapreduce/{name}":
    get:
      tags:
      - mapreduce
      summary: Returns a mapreduce
      description: Returns a mapreduce
      operationId: cloudmesh.mapreduce.get_by_name
      parameters:
        - name: name
          in: path
          description: name of the mapreduce
          required: true
          type: string
      responses:
        200:
          description: mapreduce info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mapreduce"
components:
  schemas:
    mapreduce:
      type: object
      description: An object representing a mapreduce deployment definition
      properties:
        name:
          type: string
          description: name of the mapreduce cluster
        deployment_type:
          type: string
          description: the type of the deployement framework
        deployment_git:
          type: string
          description: the url where to find the deployment scripts
        resource_managers:
          type: integer
          description: number of resource managers
        namenodes:
          type: integer
          description: number of name nodes
        datanodes:
          type: integer
          description: number of data nodes
        historynodes:
          type: integer
          description: number of history nodes
        journalnodes:
          type: integer
          description: number of journal nodes
        yarn:
          type: boolean
          description: true if yarn is used
        hdfs:
          type: boolean
          description: true if hdfs is used
        timestamp:
          description: timestamps associated with the resource
          $ref: "timestamp.yaml#/components/schemas/Timestamp"
