swagger: "2.0"
info:
  version: 3.0.1
  x-date: 05-20-2019
  title: Microservice
  description: |-
  
    As part of microservices, a function with parameters that can be
    invoked has been defined.

  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/microservices:
    get:
      tags:
      - Microservice
      summary: Returns all microservices
      description: Returns all microservices
      operationId: cloudmesh.microservice.get
      produces:
        - application/json
      responses:
        '200':
          description: microservice info
          schema:
            type: array
            items:
              $ref: '#/definitions/Microservice'
    put:
      tags:
      - Microservice
      summary: Create a new microservice
      description: Create a new microservice
      operationId: cloudmesh.microservice.put
      parameters:
        - in: body
          name: microservice
          description: The new microservice to create
          schema:
            $ref: '#/definitions/Microservice'
      responses:
        '201':
          description: Created
  '/cloudmesh/microservice/{name}':
    get:
      tags:
      - Microservice
      summary: Returns a microservice
      description: Returns a microservice
      operationId: cloudmesh.microservice.get_by_name
      parameters:
        - name: name
          in: path
          description: Get microservie info by name
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: microservice info
          schema:
            $ref: '#/definitions/Microservice'
definitions:
  Microservice:
    type: object
    description: the microservice
    properties:
      name:
        type: string
        description: name of the microservice
      endpoint:
        type: string
        description: the end point of the microservice
      function:
        type: string
        description: the function the  microservice represents
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'
