openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  title: Microservice
  description: |-
  
    As part of microservices, a function with parameters that can be
    invoked has been defined.

  termsOfService: "https://github.com/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
basePath: "/cloudmesh/v3"
paths:
  /microservices:
    get:
      tags:
      - Microservice
      summary: Returns all microservices
      description: Returns all microservices
      operationId: cloudmesh.microservice.get
      produces:
        - application/json
      responses:
        "200":
          description: microservice info
          schema:
            type: array
            items:
              $ref: "#/definitions/Microservice"
    put:
      tags:
      - Microservice
      summary: Create a new microservice
      description: Create a new microservice
      operationId: cloudmesh.microservice.put
      parameters:
        - in: body
          name: microservice
          description: The new microservice to create
          schema:
            $ref: "#/definitions/Microservice"
      responses:
        "201":
          description: Created
  "/microservice/{name}":
    get:
      tags:
      - Microservice
      summary: Returns a microservice
      description: Returns a microservice
      operationId: cloudmesh.microservice.get_by_name
      parameters:
        - name: name
          in: path
          description: Get microservie info by name
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: microservice info
          schema:
            $ref: "#/definitions/Microservice"
    put:
      tags:
        - Microservice
      summary: Uploads a microservice by name
      description: Uploads a microservice by name
      operationId: cloudmesh.microservice.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the microservice
      produces:
        - application/json
      responses:
        "200":
          description: microservice info
          schema:
            $ref: "#/definitions/Microservice"
    delete:
      tags:
        - Microservice
      summary: Deletes a microservice by name
      description: Deletes a microservice by name
      operationId: cloudmesh.microservice.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the microservice
      produces:
        - application/json
      responses:
        "200":
          description: microservice info
          schema:
            $ref: "#/definitions/Microservice"
components:
  schemas:
    Microservice:
      type: object
      description: the microservice
      properties:
        name:
          type: string
          description: name of the microservice
        endpoint:
          type: string
          description: the end point of the microservice
        function:
          type: string
          description: the function the  microservice represents
        timestamp:
          description: timestamps associated with the resource
          $ref: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/spec/timestamp.yaml#/definitions/Timestamp"
