openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  title: Nic
  description: |-
  
    A service to store Network Interface Controller (NIC) information. All of
    them are stored as Strings.

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
basePath: "/cloudmesh/v3"
paths:
  /nics:
    get:
      tags:
      - NIC
      summary: Returns all nics
      description: Returns all nics
      operationId: cloudmesh.nic.get
      produces:
        - application/json
      responses:
        "200":
          description: nic info
          schema:
            type: array
            items:
              $ref: "#/definitions/Nic"
    put:
      tags:
      - NIC
      summary: Create a new nic
      description: Create a new nic
      operationId: cloudmesh.nic.put
      parameters:
        - in: body
          name: nic
          description: The new nic to create
          schema:
            $ref: "#/definitions/Nic"
      responses:
        "201":
          description: Created
  "/nic/{name}":
    get:
      tags:
      - NIC
      summary: Returns a nic
      description: Returns a nic
      operationId: cloudmesh.nic.get_by_name
      parameters:
        - name: name
          description: Get nic info by name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: nic info
          schema:
            $ref: "#/definitions/Nic"
    put:
      tags:
        - NIC
      summary: Uploads a nic by name
      description: Uploads a nic by name
      operationId: cloudmesh.nic.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the nic
      produces:
        - application/json
      responses:
        "200":
          description: nic info
          schema:
            $ref: "#/definitions/Nic"
    delete:
      tags:
        - NIC
      summary: Deletes a nic by name
      description: Deletes a nic by name
      operationId: cloudmesh.nic.put_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the nic
      produces:
        - application/json
      responses:
        "200":
          description: nic info
          schema:
            $ref: "#/definitions/Nic"
components:
  schemas:
    Nic:
      type: object
      description: the nic
      properties:
        name:
          type: string
          description: name of the nic
        kind:
          type: string
          description: kind of the nic, such as wireless
        mac:
          type: string
          description: the mac address
        ip:
          type: string
          description: the IP address
        mask:
          type: string
          description: the network mask
        broadcast:
          type: string
          description: the broadcast address
        gateway:
          type: string
          description: the gateway address
        mtu:
          type: integer
          description: the MTU of the NIC
        bandwidth:
          type: integer
          description: the bandwidth in bps
        timestamp:
          description: timestamps associated with the resource
          $ref: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/spec/timestamp.yaml#/definitions/Timestamp"

