openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 08-06-2019
  x-status: TODO
  title: Nic
  description: |-
  
    A service to store Network Interface Controller (NIC) information.

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /nic:
    get:
      tags:
        - Nic
      summary: Returns a list of network interface controllers
      description: Returns a list of all network interface controllers
      operationId: cloudmesh.nic.list
      responses:
        '200':
          description: The list of network interface controllers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Nic'
        '400':
           description: No Nic found
        '401':
          description: Not authorized
    put:
      tags:
        - Nic
      summary: Set a network interface controller
      description: Sets the named network interface controller
      operationId: cloudmesh.nic.add
      requestBody:
        description: The new nic to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nic'
      responses:
        '200':
          description: Nic updated
        '400':
          description: Error updating network interface controller
        '401':
          description: Not authorized
  /nic/{name}:
    get:
      tags:
        - Nic
      summary: Returns the named network interface controller
      description: Returns a network interface controller by name
      operationId: cloudmesh.nic.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the network interface controller
      responses:
        '200':
          description: Returning the information of the network interface controller
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nic'
        '400':
           description: No Nic found
        '401':
          description: Not authorized
        '404':
           description: The named network interface controller could not be found
    delete:
      tags:
        - Nic
      summary: Deletes the named network interface controller
      description: Deletes a network interface controller by name
      operationId: cloudmesh.nic.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the network interface controller
      responses:
        '200':
          description: Deletion successful
        '400':
           description: No Nic found
        '401':
          description: Not authorized
        '404':
           description: The named network interface controller could not be found
components:
  schemas:
    Nic:
      type: object
      description: The network interface controller
      properties:
        name:
          type: string
          description: Name of the network interface controller
        kind:
          type: string
          description: Kind of the network interface controller (wifi, WAN, ...)
        mac:
          type: string
          description: The mac address
        ip:
          type: string
          description: The IP address
        mask:
          type: string
          description: The network mask
        broadcast:
          type: string
          description: The broadcast address
        gateway:
          type: string
          description: The gateway address
        mtu:
          type: integer
          description: The MTU of the NIC
        bandwidth:
          type: integer
          description: The bandwidth in bps

