openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 008-06-2019
  x-status: TODO
  title: Nic
  description: |-
  
    A service to store Network Interface Controller (NIC) information.

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /nic:
    get:
      tags:
        - Nic
      summary: Returns a list of nics
      description: Returns a list of all nics
      operationId: cloudmesh.nic.list
      responses:
        '200':
          description: The list of nics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Nic'
        '400':
           description: No Nic found.
        '401':
          description: Not authorized.
    put:
      tags:
        - Nic
      summary: Set a nic
      description: Sets the named nic
      operationId: cloudmesh.nic.add
      requestBody:
        description: The new nic to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nic'
      responses:
        '200':
          description: Nic updated.
        '400':
          description: Error updateing nic.
        '401':
          description: Not authorized.
  /nic/{name}:
    get:
      tags:
        - Nic
      summary: Returns the named nic
      description: Returns a nic by name
      operationId: cloudmesh.nic.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the nic
      responses:
        '200':
          description: Retruning the information of the nic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nic'
        '400':
           description: No Nic found.
        '401':
          description: Not authorized.
        '404':
           description: The named nic could not be found.
    delete:
      tags:
        - Nic
      summary: Deletes the named nic
      description: Deletes a nic by name
      operationId: cloudmesh.nic.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the nic
      responses:
        '200':
          description: Deletion successful.
        '400':
           description: No Nic found.
        '401':
          description: Not authorized.
        '404':
           description: The named nic could not be found.
components:
  schemas:
    Nic:
      type: object
      description: the nic
      properties:
        name:
          type: string
          description: name of the nic
        kind:
          type: string
          description: kind of the nic, such as wireless
        mac:
          type: string
          description: the mac address
        ip:
          type: string
          description: the IP address
        mask:
          type: string
          description: the network mask
        broadcast:
          type: string
          description: the broadcast address
        gateway:
          type: string
          description: the gateway address
        mtu:
          type: integer
          description: the MTU of the NIC
        bandwidth:
          type: integer
          description: the bandwidth in bps

