
openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 17-06-2019
  x-status: defined
  title: Network of Nodes
  description: |-

    A Network of Nodes (NON) contains a number of compute nodes that are
    connected by a network and can be reached from each other. The concept is a
    generalization of the term Network of Workstations. In contrast to a
    Virtual Cluster it doe snot have a dedicated manager node. Network of
    nodes can be real or virtual. The same security context can be used to
    authenticate to all nodes in the network of nodes. This is typically done
    with a public keystore in which all keys are stored that allow access to
    the nodes.

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup Service
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /non:
    get:
      tags:
        - Network of nodes
      summary: Returns a list of network of nodess
      description: Returns a list of all network of nodess
      operationId: cloudmesh.non.list
      responses:
        '200':
          description: The list of network of nodess
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Non'
        '401':
          description: Not authorized
  /non/{name}:
    put:
      tags:
        - Network of nodes
      summary: Uploads a network of nodes to the list of network of nodess
      description: Uploads a network of nodes to the list of network of nodess
      operationId: cloudmesh.non.add
      requestBody:
        description: The network of nodes to be uploaded
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Non'
      responses:
        '200':
          description: Network of nodes updated or created.
        '400':
          description: Error updating network of nodes
        '401':
          description: Not authorized
  /non/{name}/publickeystore:
    get:
      tags:
        - Non
      summary: Returns the information of the keystore
      description: Returns a network of nodes by name
      operationId: cloudmesh.non.keystore.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the network of nodes
      responses:
        '200':
          description: Returning the information of the network of nodes
          content:
            application/json:
              schema:
                type: string
                description: the endpoint of the publickeystore
        '401':
          description: Not authorized
    delete:
      tags:
        - Network of nodes
      summary: Deletes the keystore
      description: Deletes a network of nodes by name
      operationId: cloudmesh.non.keystore.delete
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the network of nodes
      responses:
        '200':
          description: Deletion successful
        '401':
          description: Not authorized
    put:
      tags:
        - Network of nodes
      summary: Adds a keystore
      description: Updates or adds a node to the network of nodes.
      operationId: cloudmesh.non.keystore.add
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the network of nodes
      responses:
        '200':
           description: Node keystore added sucessfully
        '401':
          description: Not authorized
  /non/{name}/node:
    get:
      tags:
        - Non
      summary: Returns the named network of nodes
      description: Returns a network of nodes by name
      operationId: cloudmesh.non.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the network of nodes
      responses:
        '200':
          description: Returning the information of the node
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Non'
        '401':
          description: Not authorized
        '404':
          description: The named network of nodes could not be found
    delete:
      tags:
        - Network of nodes
      summary: Deletes the named network of nodes
      description: Deletes a network of nodes by name
      operationId: cloudmesh.non.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the network of nodes
      responses:
        '200':
          description: Deletion successful
        '401':
          description: Not authorized
        '404':
          description: The named network of nodes could not be found
  /non/{name}/node/{node}:
    get:
      tags:
        - Network of nodes
      summary: Node of the named network of nodes
      description: Returns the specific node of the named network of nodes.
      operationId: cloudmesh.non.node.get_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the network of nodes
        - name: node
          description: The node name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Node info
          content:
            application/json:
              schema:
                $ref: "virtualcluster.yaml#/components/schemas/Node"
        '401':
          description: Not authorized
    put:
      tags:
        - Network of nodes
      summary: Updates or adds a node to the network of nodes
      description: Updates or adds a node to the network of nodes
      operationId: cloudmesh.non.node.add
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the network of nodes
        - name: node
          description: The node name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: The node to be uploaded
        required: true
        content:
          application/json:
            schema:
              $ref: "virtualcluster.yaml#/components/schemas/Node"
      responses:
        '200':
           description: Node added sucessfully
        '401':
          description: Not authorized
    delete:
      tags:
        - Network of nodes
      summary: Delete a node in the network of nodes
      description: Delete a node in the network of nodes
      operationId: cloudmesh.non.node.delete
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the network of nodes
        - name: node
          description: The node name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
           description: Deletion successful
        '401':
          description: Not authorized
components:
  schemas:
    Non:
      type: object
      properties:
        name:
          description: The name of the network of nodes
          type: string
        description:
          type: string
          description: A description of the network of nodes
        nodes:
          description: List of nodes of the network of nodes
          type: array
          items:
            $ref: "virtualcluster.yaml#/components/schemas/Node"