---
swagger: "2.0"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: defined
  title: NOW
  description: |-

    A Network of Stations (NOW) is a cluster over a selection of
    nodes. The nodes can be selected from a yaml file that contains
    all clusters and nodes. NOW can submit a batch of jobs to the
    selected nodes, and wait for the results and gather the results
    when they are ready. Alternatively the results can be retrieved
    manually at a later time.  The communication between the local
    management machine and the NOW nodes are via SSH and the authentication
    is handled with the SSH configuration file.

  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup Service
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
basePath: "/cloudmesh/v3"
paths:
  /now:
    get:
      tags:
        - NOW
      summary: Returns list of NOWs
      description: Returns list of NOWs
      operationId: cloudmesh.now.get
      produces:
        - application/json
      responses:
        200:
          description: profile info
          schema:
            type: array
            items:
              $ref: '#/definitions/NOW'
    put:
      tags:
        - NOW
      summary: Create a new NOW
      description: Create a new NOW
      operationId: cloudmesh.now.add
      parameters:
        - in: body
          name: now
          description: The new NOW to create
          required: true
          schema:
            $ref: '#/definitions/NOW'
      responses:
        201:
          description: Created

  /now/{nowname}:
    get:
      tags:
        - NOW
      summary: Returns a now by its name
      description: Returns a now by its name
      operationId: cloudmesh.now.getByName
      parameters:
        - name: nowname
          in: path
          required: true
          description: name of the now
          type: string
      produces:
        - application/json
      responses:
        200:
          description: now info
          schema:
            $ref: '#/definitions/NOW'

  /now/{nowname}/{nodename}:
    get:
      tags:
        - NOW
      summary: Returns the specified node info of the specified now
      description: Returns the specified node info of the specified now
      operationId: cloudmesh.now.getNodeByName
      parameters:
        - name: nowname
          in: path
          required: true
          description: name of the now
          type: string
        - name: nodename
          in: path
          required: true
          description: name of the node
          type: string
      produces:
        - application/json
      responses:
        200:
          description: NOW node info
          schema:
            $ref: '#/definitions/NowNode'

  /now/jobs/{jobname}:
    get:
      tags:
        - NOW
      summary: Returns the specified job info submitted to a now
      description: Returns the specified job info submitted to a now
      operationId: cloudmesh.now.getJobByName
      parameters:
        - name: jobname
          description: name of the job
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: job info
          schema:
            $ref: '#/definitions/NowNode'

definitions:
  NOW:
    type: object
    properties:
      name:
        description: The name of the now
        type: string
      description:
        type: string
        description: A description of the now
      runtime-config:
        description: The type of input and output of the jobs in the now
        type: array
        items:
          $ref: '#/definitions/RuntimeConfig'
      nodes:
        description: List of nodes of the now
        type: array
        items:
          $ref: '#/definitions/NowNode'
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'

  RuntimeConfig:
    type: object
    properties:
      input:
        type: string
        description: the type of input for the jobs submitted to NOW, possible values are params or params+file
      output:
        type: string
        description: the type of input for the jobs submitted to NOW, possible values are stdout, file or file+stdout

  NowNode:
    type: object
    properties:
      name:
        type: string
        description: name of the node
      label:
        type: string
        description: label of the node
      address:
        type: string
        description: address of the node (IP or URL)
      credentials:
        type: array
        description: credential information for connecting to the node
        items:
          $ref: '#/definitions/Credentials'

  Credentials:
    type: object
    properties:
      cred_type:
        type: string
        description: type of the credentials
      username:
        type: string
        description: username for conenction
      publickey:
        type: string
        description: path to the publickey
      sshconfigpath:
        type: string
        description: path to the ssh config which is used for connecting to the node

  Path:
    type: object
    description: path information
    properties:
      folder_path:
        type: string
        description: absolute path to the folder
      file_path:
        type: string
        description: absolute path to the file
      file_name:
        type: string
        description: the name of the script/file

  Job:
    type: object
    properties:
      suffix:
        type: string
        description: suffix of the job in the remote
      nowname:
        type: string
        description: name of the NOW on which job is submitted
      job_runtimeconfig:
        type: array
        description: type of the runtime config used for the job
        items:
          $ref: '#/definitions/RuntimeConfig'
      script_path_remote:
        type: array
        description: script path information in remote NOW
        items:
          $ref: '#/definitions/Path'
      argfiles_path_remote:
        type: array
        description: argument files path information in remote NOW
        items:
          $ref: '#/definitions/Path'
      script_path_local:
        type: array
        description: script path information locally
        items:
          $ref: '#/definitions/Path'
      argfiles_path_local:
        type: array
        description: argument files path information locally
        items:
          $ref: '#/definitions/Path'
      results_folder:
        type: array
        description: local folder to copy the results
        items:
          $ref: '#/definitions/Path'
      node_pids:
        type: array
        description: pid in each node
        items:
          $ref: '#/definitions/NodePid'

  NodePid:
    type: object
    properties:
      node:
        type: array
        description: node information
        items:
          $ref: '#/definitions/NowNode'
      pid:
        type: string
        description: pid number in remote node
