openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 17-06-2019
  x-status: defined
  title: Organization
  description: |-

    An important concept in many services is the management of a group
    of users in an organization. Within an organization we distinguish
    different groups of users. Groups can be used to charachterize roles
    users can fulfill. Users can belong to multiple groups. Such groups can
    also be used to specify access rights to services.

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /organization:
    get:
      tags:
        - Organization
      summary: Returns a list of organizations
      description: Returns a list of all organizations
      operationId: cloudmesh.organization.list
      responses:
        '200':
          description: The list of organizations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
        '401':
          description: Not authorized
  /organization/{name}:
    get:
      tags:
        - Organization
      summary: Returns the named organization
      description: Returns an organization by name
      operationId: cloudmesh.organization.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the organization
      responses:
        '200':
          description: Retruning the information of the organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '401':
          description: Not authorized
        '404':
           description: The named organization could not be found
    put:
      tags:
        - Organization
      summary: Uploads an organization to the list of organizations
      description: Uploads an organization to the list of organizations
      operationId: cloudmesh.organization.add
      requestBody:
        description: The organization to be uploaded
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
      responses:
        '200':
          description: Organization created or updated
        '401':
          description: Not authorized
        '404':
          description: The organization could not be found
    delete:
      tags:
        - Organization
      summary: Deletes the named organization
      description: Deletes an organization by name
      operationId: cloudmesh.organization.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the organization
      responses:
        '200':
          description: Deletion successful
        '401':
          description: Not authorized
        '404':
           description: The named organization could not be found
  /organization/{name}/user:
    get:
      tags:
        - Organization
      summary: Returns all users of the organization
      description: Returns all users of the organization
      operationId: cloudmesh.organization.user.list
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the organization
      responses:
        '200':
          description: The organization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
        '401':
          description: Not authorized
  /organization/{name}/user/{user}:
    get:
      tags:
        - Organization
      summary: Returns the specific user of that organization
      description: Returns the specific user of that organization
      operationId: cloudmesh.organization.user.get_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the organization
        - name: user
          description: The user name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The user
          content:
            application/json:
              schema:
                $ref: "user.yaml#/components/schemas/User"
        '401':
          description: Not authorized
        '404':
          description: The organization or user could not be found
    put:
      tags:
        - Organization
      summary: Updates or adds a user in the organization
      description: Updates or adds a user in the organization
      operationId: cloudmesh.organization.user.add
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the organization
        - name: user
          description: The user name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: The user to be uploaded
        required: true
        content:
          application/json:
            schema:
              $ref: 'user.yaml#/components/schemas/User'
      responses:
        '200':
          description: User added sucessfully
        '401':
          description: Not authorized
        '404':
          description: The organization or user could not be found\
    delete:
      tags:
        - Organization
      summary: Delete an user in the organization
      description: Delete an user in the organization
      operationId: cloudmesh.organization.user.delete
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the organization
        - name: user
          description: The user name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deletion successful
        '401':
          description: Not authorized
        '404':
          description: The organization or user could not be found
  /organization/{name}/group/:
    get:
      tags:
        - Organization
      summary: Returns all group names
      description: Returns all group names
      operationId: cloudmesh.organization.group.list
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the organization
      responses:
        '200':
          description: Returning the information of the group
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
           description: No group found
        '401':
          description: Not authorized
        '404':
           description: The organization or group could not be found
  /organization/{name}/group/{group}:
    get:
      tags:
        - Organization
      summary: Returns the specific group of that organization
      description: Returns the specific group of that organization
      operationId: cloudmesh.organization.group.get_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the organization
        - name: group
          description: The group name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The group
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
        '401':
          description: Not authorized
        '404':
          description: The organization or group could not be found
    put:
      tags:
        - Organization
      summary: Updates or adds a group in the organization
      description: Updates or adds a group in the organization
      operationId: cloudmesh.organization.group.add
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the group
        - name: group
          description: The group name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Group added sucessfully
        '401':
          description: Not authorized
        '404':
          description: The organization or group could not be found
    delete:
      tags:
        - Organization
      summary: Delete a group in the organization
      description: Delete a group in the organization
      operationId: cloudmesh.organization.greop.delete
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the organization
        - name: group
          description: The group name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deletion successful
        '401':
          description: Not authorized
        '404':
          description: The organization or group could not be found
  /organization/{name}/group/{group}/{user}:
    put:
      tags:
        - Organization
      summary: Updates or adds a user name to the group
      description: Updates or adds a user name to the group
      operationId: cloudmesh.organization.group.user.add
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the group
        - name: group
          description: The group name
          in: path
          required: true
          schema:
            type: string
        - name: user
          description: The user name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User added sucessfully
        '401':
          description: Not authorized
        '404':
          description: The organization, group, or user could not be found
    delete:
      tags:
        - Organization
      summary: Delete a user in the group
      description: Delete a user in the group
      operationId: cloudmesh.organization.greop.delete.user
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the organization
        - name: group
          description: The group name
          in: path
          required: true
          schema:
            type: string
        - name: user
          description: The user name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deletion successful
        '401':
          description: Not authorized
        '404':
          description: The organization, group, or user could not be found
components:
  schemas:
    Organization:
      type: object
      properties:
        name:
          description: Name of the organization
          type: string
        users:
          description: List of users
          type: array
          items:
            $ref: "user.yaml#/components/schemas/User"
    Group:
      type: object
      description: The groups
      properties:
        name:
          type: string
          description: The name of the group
        description:
          type: string
          description: The description of the group
        users:
          description: The user names that are members of the group
          type: array
          items:
            type: string

