swagger: "2.0"
info:
  version: 3.1.1
  x-status: defined
  x-date: 02-15-2019
  title: Replica
  description: |-
  
    In many distributed systems, it is important that a file can be
    replicated among different systems to provide faster access. It is
    important to provide a mechanism to trace the pedigree of the file
    while pointing to its original source. 

  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
basePath: "/cloudmesh/v3"
paths:
  /replica:
    get:
      tags:
      - Replica
      summary: Returns all replicas records
      description: Returns all replicas records
      operationId: cloudmesh.replica.get
      produces:
        - application/json
      responses:
        200:
          description: replica info
          schema:
            type: array
            items:
              $ref: '#/definitions/Replica'
    put:
      tags:
      - Replica
      summary: Create a new replica
      description: Create a new replica      
      operationId: cloudmesh.replica.add
      parameters:
        - in: body
          name: replica
          required: true
          description: The new replica entry to create
          schema:
            $ref: '#/definitions/Replica'
      responses:
        201:
          description: Created
  '/replica/{name}':
    get:
      tags:
      - Replica
      summary: Returns a replica by name
      description: Returns a replica by name
      operationId: cloudmesh.replica.get_by_name
      parameters:
        - name: name
          description: name of the replica entry
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: replica info
          schema:
            $ref: '#/definitions/Replica'
definitions:
  Replica:
    type: object
    description: An entry representing a file replica record
    properties:
      name:
        type: string
        description: the name of the replica
      filename:
        type: string
        description: the original filename
      endpoint:
        type: string
        description: The location of the file
      checksum:
        type: string
        description: The checksum of the file
      size:
        type: integer
        description: The size of the file in byte
      timestamp:
        $ref: '#/definitions/Timestamp'
        description: The timestamp of the replica. The timestamp refers to when this entry has been accessed or changed, not the object this replica is pointing to.

