openapi: '3.0.2'
info:
  version: 3.2.0
  x-date: 14-06-2019
  x-status: defined
  title: Reservation
  description: |-
  
    Some services may consume a considerable amount of resources,
    necessitating the reservation of resources.
    
  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /reservation:
    get:
      tags:
        - Reservation
      summary: Returns a list of reservations
      description: Returns a list of all reservations
      operationId: cloudmesh.reservation.list
      responses:
        '200':
          description: The list of reservations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
        '400':
          description: No Reservations found
    put:
      tags:
        - Reservation
      summary: Uploads a reservation to the list of reservations
      description: Uploads a reservation to the list of reservations
      operationId: cloudmesh.reservation.add
      requestBody:
        description: The reservation to be uploaded
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
      responses:
        '200':
          description: Reservation updated
        '400':
          description: Error updating reservation
  /reservation/{name}:
    get:
      tags:
        - Reservation
      summary: Returns the named reservation
      description: Returns an reservation by name
      operationId: cloudmesh.reservation.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the reservation
      responses:
        '200':
          description: Returning the information of the reservation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
        '400':
          description: No reservation found
        '401':
          description: Not authorized
        '404':
          description: The named reservation could not be found
    delete:
      tags:
        - Reservation
      summary: Deletes the named reservation
      description: Deletes an reservation by name
      operationId: cloudmesh.reservation.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the reservation
      responses:
        '200':
          description: Deletion successful
        '400':
          description: No reservation found
        '401':
          description: Not authorized
        '404':
          description: The named reservation could not be found
components:
  schemas:
    Reservation:
      type: object
      description: The reservation
      properties:
        name:
          type: string
          description: Name of the reservation
        service:
          type: string
          description: The name of the service on which we reserve
        description:
          type: string
          description: The description of the reservation
        start:
          type: string
          format: date
          description: The start time and date
        end:
          type: string
          format: date
          description: The end time and date
