swagger: "2.0"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: defined
  title: Scheduler
  description: |-
  
    The scheduler is a service to store scheduler, value, and type information, all of which
    are stored as strings.
    
  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
basePath: "/cloudmesh/v3"
paths:
  /schedulers:
    get:
      tags:
      - Scheduler
      summary: Returns all schedulers
      description: Returns all schedulers
      operationId: cloudmesh.scheduler.get
      produces:
        - application/json
      responses:
        '200':
          description: scheduler info
          schema:
            type: array
            items:
              $ref: '#/definitions/Scheduler'
    put:
      tags:
      - Scheduler
      summary: Create a new scheduler
      description: Create a new scheduler
      operationId: cloudmesh.scheduler.add
      parameters:
        - in: body
          name: scheduler
          description: The new scheduler to create
          schema:
            $ref: '#/definitions/Scheduler'
      responses:
        '201':
          description: Created
  '/scheduler/{name}':
    get:
      tags:
      - Scheduler
      summary: Returns a scheduler
      description: Returns a scheduler
      operationId: cloudmesh.scheduler.get_by_name
      parameters:
        - name: name
          description: name of the scheduler
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: scheduler info
          schema:
            $ref: '#/definitions/Scheduler'
definitions:
  Scheduler:
    type: object
    description: the scheduler
    properties:
      name:
        type: string
        description: name of the scheduler
      value:
        type: string
        description: information of the scheduler
      kind:
        type: string
        description: the scheduler kind or type
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'
