openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 008-06-2019
  x-status: TODO
  title: Secgroup
  description: |-
  
   A security group defines the incoming and outgoing security rules
   which can then be assigned to a node when a node is being created.
   Once the node is up the connection to and from the node will be
   decided by the security group rules, in addition to any other possible
   rules applied on network devices or from the instance"s firewall
   settings.
   A security group may have one or multiple rules and a node may be
   associated with one or more security groups.
   
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /secgroup:
    get:
      tags:
      - Secgroup
      summary: Returns all secgroups
      description: Returns all secgroups
      operationId: cloudmesh.secgroup.get
      responses:
        '200':
          description: secgroup info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Secgroup"
        '400':
          description: Not found.
  /secgroup/{name}:
    get:
      tags:
      - Secgroup
      summary: Return the secgroup by name
      description: Return the secgroup by name
      operationId: cloudmesh.secgroup.get_by_name
      parameters:
        - name: name
          description: name of the security group
          in: path
          required: true
          type: string
      responses:
        '200':
          description: secgroup info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Secgroup"
        '400':
          description: Not found.
    post:
      tags:
      - Secgroup
      summary: Create a new named secgroup
      description: Create a new named secgroup
      operationId: cloudmesh.secgroup.add
      parameters:
        - in: path
          name: name
          required: true
          description: The name of the secgroup to create
          schema:
            type: string
      responses:
        '201':
          description: Created
  /secgroup/{name}/rule:
    post:
      tags:
      - Secgroup
      summary: Create a new rule in the specified security group
      description: Create a new rule in secgroup
      operationId: cloudmesh.secgroup.add_rule
      parameters:
        - in: path
          name: name
          required: true
          description: The name of the new secgroup to create
          type: string
      requestBody:
        description: The new secgroup rule to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SecGroupRule'
      responses:
        '200':
          description: Created
        '400':
          description: Not found.
  "/secgroup/{name}/rule/{rule}":
    get:
      tags:
      - Secgroup
      summary: Get an existing rule from the specified security group
      description: Create a new rule in secgroup
      operationId: cloudmesh.secgroup.get_rule
      parameters:
        - in: path
          name: name
          required: true
          description: The named of the secgroup from which the rule will be deleted
          type: string
        - in: path
          name: rule
          required: true
          description: The uuid of the rule to be deleted
          type: string
      responses:
        '200':
          description: The security group rule definition info
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/SecGroupRule"
        '400':
          description: Not found.
    delete:
      tags:
      - Secgroup
      summary: Delete an existing rule from the specified security group
      description: Create a new rule in secgroup
      operationId: cloudmesh.secgroup.delete_rule
      parameters:
        - in: path
          name: name
          required: true
          description: The named of the secgroup from which the rule will be deleted
          type: string
        - in: path
          name: rule
          required: true
          description: The uuid of the rule to be deleted
          type: string
      responses:
        '200':
          description: Deleted.
        '400':
          description: Not found.
components:
  schemas:
    Secgroup:
      type: object
      description: the security group object
      properties:
        uuid:
          type: string
          description: Unique identifier of the security group
        name:
          type: string
          description: name of the secgroup
        description:
          type: string
          description: describes what the secgroup is for
        rules:
          type: array
          description: List of Secgroup rules
          items:
            $ref: "#/components/schemas/SecGroupRule"
    SecGroupRule:
      type: object
      description: security group rule
      properties:
        uuid:
          type: string
          description: Unique identifier of the rule
        ingress:
          type: boolean
          description: The defined security group rule is for ingress if True
        egress:
          type: boolean
          description: The defined security group rule is for egress if True
        remote_group:
          type: string
          description: Name of the group if the rule is defined by group instead of IP range
        protocol:
          type: string
          description: The protocol used such as TCP, UDP, ICMP
        from_port:
          type: integer
          description: Port range starting port
        to_port:
          type: integer
          description: Port range ending port
        cidr:
          type: string
          description: The source or destination network in CIDR notation, e.g., 129.79.0.0/16
