openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  title: Stream
  description: |-
  
   The stream object describes a data flow, providing information
   about the rate and number of items exchanged while issuing requests
   to the stream. A stream may return data items in a specific format
   that is defined by the stream.

   
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
servers:
  - url: /cloudmesh/v3
paths:
  /streams:
    get:
      tags:
        - Stream
      summary: Returns all streams
      description: Returns all streams
      operationId: cloudmesh.stream.get
      produces:
        - application/json
      responses:
        200:
          description: stream info
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Stream"
    put:
      tags:
        - Stream
      summary: Create a new stream
      description: Create a new stream
      operationId: cloudmesh.stream.add
      parameters:
        - in: body
          name: stream
          description: The new stream to create
          schema:
            $ref: "#/components/schemas/Stream"
      responses:
        "201":
          description: Created
  "/stream/{name}":
    get:
      tags:
        - Stream
      summary: Returns a stream
      description: Returns a stream
      operationId: cloudmesh.stream.get_by_name
      parameters:
        - name: name
          description: Get stream info by name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: stream info
          schema:
            $ref: "#/components/schemas/Stream"

components:
  schemas:
    Stream:
      type: object
      description: the stream
      properties:
        name:
          type: string
          description: name of the stream
        format:
          type: string
          description: format of the stream
        rate:
          type: integer
          description: the rate of messages
        limit:
          type: integer
          description: the limit of items send
        timestamp:
          description: timestamps associated with the resource
          $ref: "timestamp.yaml#/components/schemas/Timestamp"
