swagger: "2.0"
info:
  version: 3.0.2
  x-date: 10-30-2018
  title: Stream
  description: |-
  
   The stream object describes a data flow, providing information
   about the rate and number of items exchanged while issuing requests
   to the stream. A stream may return data items in a specific format
   that is defined by the stream.

   
  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/streams:
    get:
      tags:
        - Stream
      summary: Returns all streams
      description: Returns all streams
      operationId: cloudmesh.stream.get
      produces:
        - application/json
      responses:
        '200':
          description: stream info
          schema:
            type: array
            items:
              $ref: '#/definitions/Stream'
    put:
      tags:
        - Stream
      summary: Create a new stream
      description: Create a new stream
      operationId: cloudmesh.stream.add
      parameters:
        - in: body
          name: stream
          description: The new stream to create
          schema:
            $ref: '#/definitions/Stream'
      responses:
        '201':
          description: Created
  '/cloudmesh/stream/{name}':
    get:
      tags:
        - Stream
      summary: Returns a stream
      description: Returns a stream
      operationId: cloudmesh.stream.get_by_name
      parameters:
        - name: name
          description: Get stream info by name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: stream info
          schema:
            $ref: '#/definitions/Stream'
definitions:
  Stream:
    type: object
    description: the stream
    properties:
      name:
        type: string
        description: name of the stream
      format:
        type: string
        description: format of the stream
      rate:
        type: integer
        description: the rate of messages
      limit:
        type: integer
        description: the limit of items send
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'
