openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 08-06-2019
  x-status: TODO
  title: Timestamp
  description: |-
  
    Data often needs to be timestamped to indicate when it has been
    accessed, created, or modified. All objects defined in this
    document will have, in their final version, a timestamp.
    The date-time string is defined in
    [RFC3339](https://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14).

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /timestamp:
    get:
      summary: Returns the time
      description: Returns the time to be used in a timestamp
      responses:
        '200':
          description: the current time and date
          content:
            text/plain:
              schema:
                type: string
                example: 1985-04-12T23:20:50.52Z
components:
  schemas:
    Timestamp:
      type: object
      description: the timestamp
      properties:
        accessed:
          type: string
          format: date-time
          description: The time stamp when the object was last accessed
          example: 1985-04-12T23:20:50.52Z
        created:
          type: string
          format: date-time
          description: The time stamp when the object was created
          example: 1985-04-12T23:20:50.52Z
        modified:
          type: string
          format: date-time
          description: The time stamp when the object was modified
          example: 1985-04-12T23:20:50.52Z
