openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 14-06-2019
  x-status: defined
  title: Variables
  description: |-
  
    Variables are a simple string key value storage to store simple
    values. Each variable can have a datatype, so that it can be used for
    serialization into other formats. Internally they are storred as strings.

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /variable:
    get:
      tags:
        - Variable
      summary: Returns a the variables
      description: Returns the variables
      operationId: cloudmesh.variable.list
      responses:
        '200':
          description: The list of variables
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Variable'
        '400':
           description: No variable found
    put:
      tags:
        - Variable
      summary: Set the value of a variable
      description: Set the value of the named variable
      operationId: cloudmesh.variable.add
      requestBody:
        description: The variable and its value
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Variable'
      responses:
        '200':
          description: Variable updated
        '400':
          description: Error updating variable
        '401':
          description: Not authorized
  /variable/{name}:
    get:
      tags:
        - Variable
      summary: Returns the named variable
      description: Returns the named variable
      operationId: cloudmesh.variable.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the variable
      responses:
        '200':
          description: Returning the information of the variable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Variable'
        '400':
           description: No variable found
        '401':
          description: Not authorized
        '404':
           description: The named variable could not be found
    delete:
      tags:
        - Variable
      summary: Deletes the named variable
      description: Deletes a variable by name
      operationId: cloudmesh.variable.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the variable
      responses:
        '200':
          description: Deletion successful
        '400':
           description: No variable found
        '401':
          description: Not authorized
        '404':
           description: The named variable could not be found
components:
  schemas:
    Variable:
      type: object
      description: the variables
      properties:
        name:
          type: string
          description: Name of the variable
        value:
          type: string
          description: Type of the variable
        description:
          type: string
          description: A description of the variable
        datatype:
          type: string
          description: The data type of the variable which can be used for
                       serialization