swagger: "2.0"
info:
  version: 3.1.1
  x-status: defined
  x-date: 02-15-2019
  title: Variables
  description: |-
  
    Variables are used to store simple values. Each variable can have
    a type, which is also provided as demonstrated in the object
    below. The variable value format is defined as string to allow
    maximal probability.
    
  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
basePath: "/cloudmesh/v3"
paths:
  /variables:
    get:
      tags:
        - Variables
      summary: Returns all variabless
      description: Returns all variabless
      operationId: cloudmesh.variables.get
      produces:
        - application/json
      responses:
        200:
          description: variables info
          schema:
            type: array
            items:
              $ref: '#/definitions/Variables'
    put:
      tags:
        - Variables
      summary: Create a new variables
      description: Create a new variables
      operationId: cloudmesh.variables.add
      parameters:
        - in: body
          name: variables
          description: The new variables to create
          schema:
            $ref: '#/definitions/Variables'
      responses:
        201:
          description: Created
  '/variables/{name}':
    get:
      tags:
        - Variables
      summary: Returns a variables
      description: Returns a variables
      operationId: cloudmesh.variables.get_by_name
      parameters:
        - name: name
          description: Name of the variable
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: variables info
          schema:
            $ref: '#/definitions/Variables'
definitions:
  Variables:
    type: object
    description: the variables
    properties:
      name:
        type: string
        description: name of the variable
      value:
        type: string
        description: type of the variable
      kind:
        type: string
        description: value of the variable
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'
