
openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: defined
  title: "Virtual Cluster"
  description: |-

    A Virtual Cluster is modeled as one Front-end, or manager node, and one or
    multiple compute nodes. The manager node usually served as a login node and
    can be accessed from outside via a public IP. The compute nodes are
    connected to the manager node via a private, usually high performance (high
    throughput and low latency), network and thus accessible only from the
    manager node. To use the virtual cluster, you login to the manager node, and
    from there you can login to any compute node, or submit a job to run on the
    compute nodes.
    
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup Service
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
basePath: "/cloudmesh/v3"
paths:
  /virtualcluster/virtualcluster:
    get:
      tags:
        - Virtualcluster
      summary: Returns all virtual clusters
      description: Returns all virtual clusters
      operationId: cloudmesh.virtualcluster.get
      produces:
        - application/json
      responses:
        200:
          description: profile info
          schema:
            type: array
            items:
              $ref: "#/components/schemas/VirtualCluster"
    put:
      tags:
        - Virtualcluster
      summary: Create a new virtual cluster
      description: Create a new virtual cluster
      operationId: cloudmesh.virtualcluster.add
      parameters:
        - in: body
          name: virtualcluster
          description: The new virtual cluster to create
          required: true
          schema:
            $ref: "#/components/schemas/VirtualCluster"
      responses:
        "201":
          description: Created
  /virtualcluster/virtualcluster/{virtualclustername}:
    get:
      tags:
        - Virtualcluster
      summary: Returns a virtual cluster by its name
      description: Returns a virtual cluster by its name
      operationId: cloudmesh.virtualcluster.getByName
      parameters:
        - name: virtualclustername
          description: name of the virtual cluster
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: virtualcluster info
          schema:
            $ref: "#/components/schemas/VirtualCluster"
  /virtualcluster/virtualcluster/{virtualclustername}/manager:
    get:
      tags:
        - Virtualcluster
      summary: Returns the manager node info of the specified virtual cluster
      description: Returns the manager node info of the specified virtual cluster
      operationId: cloudmesh.virtualcluster.getManagerByName
      parameters:
        - name: virtualclustername
          description: name of the virtua cluster
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: virtual cluster manager node info
          schema:
            $ref: "#/components/schemas/Node"
  /virtualcluster/virtualcluster/{virtualclustername}/{nodename}:
    get:
      tags:
        - Virtualcluster
      summary: Returns the specified node info of the specified virtualcluster
      description: Returns the specified node info of the specified virtualcluster
      operationId: cloudmesh.virtualcluster.getNodeByName
      parameters:
        - name: virtualclustername
          description: name of the virtua cluster
          in: path
          required: true
          type: string
        - name: nodename
          description: name of the name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: virtualcluster node info
          schema:
            $ref: "#/components/schemas/Node"
components:
  schemas:
    VirtualCluster:
      type: object
      properties:
        name:
          description: The name of the virtual cluster
          type: string
        description:
          type: string
          description: A description of the virtual cluster
        nnodes:
          type: integer
          description: number of nodes of the virtual cluster
        owner:
          type: string
          description: owner of the virtual cluster
        manager:
          description: Manager node of the virtual cluster
          $ref: "#/components/schemas/Node"
        nodes:
          description: List of nodes of the virtual cluster
          type: array
          items:
            $ref: "#/components/schemas/Node"
        timestamp:
          description: timestamps associated with the resource
          $ref: "timestamp.yaml#/components/schemas/Timestamp"

    Node:
      type: object
      properties:
        name:
          type: string
          description: name of the node
        state:
          type: string
          description: power state of the node
        ncpu:
          type: integer
          description: number of virtual CPUs of the node
        ram:
          type: string
          description: RAM size of the node
        disk:
          type: string
          description: Disk size of the node
        nics:
          type: array
          description: List of network interfaces of the node
          items:
            $ref: "#/components/schemas/NIC"
    NIC:
      type: object
      properties:
        mac:
          type: string
          description: MAC address of the node
        ip:
          type: string
          description: IP address of the node
