---
swagger: "2.0"
info:
  version: 3.1.1
  x-date: 02-15-2019
  x-status: defined
  title: Virtualdirectory
  description: |-
  
    A virtual directory is a collection of files or replicas of the
    files.  A virtual directory can contain a number of entities
    including files, streams, and other virtual directories as part of
    a collection.  The element in the collection can either be defined
    by uuid or by name.

  termsOfService: 'https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup Service Example
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  httpbasic:
    type: basic
  apikey:
    type: apiKey
    in: query
    name: api_key
  apisecret:
    type: apiKey
    in: query
    name: api_secret
basePath: "/cloudmesh/v3"
paths:
  /virtualdirectory:
    get:
      tags:
        - Virtualdirectory
      summary: Returns all virtualdirectorys
      description: Returns all virtualdirectorys
      operationId: cloudmesh.virtualdirectory.get
      produces:
        - application/json
      security:
        - httpbasic: []
      responses:
        '200':
          description: virtualdirectory info
          schema:
            type: array
            items:
              $ref: '#/definitions/Virtualdirectory'
        '401':
          description: unauthorized error
          schema:
            $ref: '#/definitions/UnauthorizedError'
    put:
      tags:
        - Virtualdirectory
      summary: Create a new virtualdirectory
      description: Create a new virtualdirectory
      operationId: cloudmesh.virtualdirectory.add
      parameters:
        - in: body
          name: virtualdirectory
          required: true
          description: The new virtualdirectory to create
          schema:
            $ref: '#/definitions/Virtualdirectory'
      security:
        - apikey: []
          apisecret: []
      responses:
        '201':
          description: Created
  '/virtualdirectory/{name}':
    get:
      tags:
        - Virtualdirectory
      summary: Returns a virtualdirectory by name
      description: Returns a virtualdirectory by name
      operationId: cloudmesh.virtualdirectory.get_by_name
      parameters:
        - name: name
          description: name of the virtual directory
          in: path
          required: true
          type: string
      produces:
        - application/json
      security:
        - httpbasic: []
      responses:
        '200':
          description: virtualdirectory info
          schema:
            $ref: '#/definitions/Virtualdirectory'
definitions:
  UnauthorizedError:
    type: object
    description: unauthorized error
    properties:
      code:
        type: string
        description: Code form of the error
      message:
        type: string
        description: Human readable form of the error
  Virtualdirectory:
    type: object
    description: the virtualdirectory
    properties:
      name:
        description: The name of the virtual directory
        type: string
      description:
        description: description of the virtual directory
        type: string
      host:
        description: remote host of the virtual directory
        type: string
      location:
        description: remote location, e.g., a directory with full path on a host
        type: string
      protocol:
        description: access protocol, e.g., HTTP, FTP, SSH, etc.
        type: string
      credential:
        description: credential to access, e.g., username, password
        type: object
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'

