openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 05-23-2019
  x-status: defined
  title: Virtual Machine
  description: |-

    VM is a service to manage virtual machines.
    
  termsOfService: https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt
  contact:
    name: NIST BDRA Interface Subgroup Service
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /vm:
    get:
      tags:
        - VM
      summary: Returns the list of the vms
      description: Returns the list of the vms
      operationId: cloudmesh.vm.get
      parameters:
        - name: cloud
          in: query
          type: string
          description: "specify the cloud from which we list, if ommitted all clouds are returned."
          required: false
      responses:
        200:
          description: Listing the VMs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/VM"
components:
  schemas:
    VM:
      type: object
      properties:
        provider:
          type: string
          description: Name of the provider
        id:
          type: string
          description: a unique id for the vm
        name:
          type: string
          description: the name of the vm
        image:
          type: string
          description: the image for the vm
        region:
          type: string
          description: an optional region
        size:
          type: string
          description: The size of the vm
        state:
          type: string
          description: The state of the vm
        private_ips:
          type: string
          description: The private IPs
        public_ips:
          type: string
          description: The public IPS
        metadata:
          type: string
          description: The meta data passed along to the VM
        timestamp:
          description: timestamps associated with the resource
          $ref: "timestamp.yaml#/components/schemas/Timestamp"
      example:
        image: image
        metadata: metadata
        size: size
        provider: provider
        name: name
        private_ips: private_ips
        id: id
        state: state
        region: region
        public_ips: public_ips
