openapi: "3.0.2"
info:
  version: 0.0.2
  x-date: 10-30-2018
  title: abc
  description: |-
  
    A service to store abc, value, type information. All of them are
    stored as Strings.
    
  termsOfService: "http://bin.io/terms/"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/abcstore/abcs:
    get:
      tags:
      - ABC
      summary: Returns all general description abcs
      description: Returns all general description abcs
      operationId: cloudmesh.abc.get
      produces:
        - application/json
      responses:
        200:
          description: abc info
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Abc"
    put:
      tags:
      - ABC
      summary: Create a new abc
      description: Create a new abc
      operationId: cloudmesh.abc.put
      parameters:
        - in: body
          name: abc
          description: The new abc to create
          schema:
            $ref: "#/components/schemas/Abc"
      responses:
        "201":
          description: Created
  "/cloudmesh/abcstore/abc/{name}":
    get:
      tags:
      - ABC
      summary: Returns a general description of a abc
      description: Returns a general description of a abc
      operationId: cloudmesh.abc.get_by_name
      parameters:
        - name: name
          description: Get abc info by name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: abc info
          schema:
            $ref: "#/components/schemas/Abc"
definitions:
  Abc:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      value:
        type: string
      kind:
        type: string
